name: mo_app
description: "MO - Marketplace."

publish_to: 'none'
version: 1.0.0+1

environment:
  # sdk: ^3.9.2
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.3
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  another_stepper: ^1.2.2
  http: ^1.1.2
  retry: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  badges: ^3.1.2
  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.3
  flutter_chat_bubble: ^2.0.2
  webview_flutter: ^4.13.0
  textfield_tags: ^3.0.1
  google_sign_in: ^7.1.1
  firebase_messaging: ^16.0.1
  location: ^7.0.1
  sentry_flutter: ^9.6.0
  payhere_mobilesdk_flutter: ^3.0.4
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  json_annotation: ^4.9.0
  firebase_core: ^4.1.0
  flutter_typeahead: ^5.2.0
  geocoding: ^4.0.0
  dio: ^5.4.1
  path: ^1.9.0
  url_launcher: ^6.2.5
  go_router: ^15.1.2
  share_plus: ^11.1.0
  top_snackbar_flutter: ^3.1.0
  timeago: ^3.6.1
  flutter_config: ^2.0.2
  screenshot: ^3.0.0
  gal: ^2.3.2
  permission_handler: ^11.3.0
  modal_bottom_sheet: ^3.0.0
  flutter_image_compress: ^2.2.0
  appsflyer_sdk: ^6.14.3
  sms_autofill: ^2.3.1
  pin_code_fields: ^8.0.1
  flutter_local_notifications: ^19.4.1
  pdf: ^3.10.8
  path_provider: ^2.1.3
  animations: ^2.0.11
  firebase_analytics: ^12.0.1
  easy_localization: ^3.0.7
  firebase_remote_config: ^6.0.1
  custom_sliding_segmented_control: ^1.8.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.1.0
  cloud_firestore: ^6.0.1
  flutter_contacts: ^1.1.9+2
  geolocator: ^13.0.2
  clipboard: ^2.0.2
  maps_launcher: ^3.0.0+1
  flutter_media_downloader: ^2.0.0
  camerawesome: ^2.0.1
  open_file: ^3.2.1
  image_cropper: ^9.1.0
  animated_custom_dropdown: ^3.1.1
  percent_indicator: ^4.2.3
  logger: ^2.4.0
  focus_on_it: ^2.0.1
  video_player: ^2.9.2
  mixpanel_flutter: ^2.0.0
  device_info_plus: ^11.3.0
  android_id: ^0.4.0
  facebook_app_events: ^0.20.1
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true