name: mo_app
description: "MO - Marketplace."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # First 10
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.3
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  another_stepper: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true