name: mo_app
description: "MO - Marketplace."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # First 10
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.3
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  another_stepper: ^1.2.2
  # Second 10
  http: ^1.1.2
  retry: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  badges: ^3.1.2
  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.3
  flutter_chat_bubble: ^2.0.2
  webview_flutter: ^4.13.0
  textfield_tags: ^3.0.1
  # Third 10
  google_sign_in: ^7.1.1
  firebase_messaging: ^16.0.1
  location: ^8.0.1
  sentry_flutter: ^9.6.0
  payhere_mobilesdk_flutter: ^3.0.4
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  json_annotation: ^4.9.0
  firebase_core: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true